# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 215a5ff0fb37fd7550cc5f48d4530eadd0bae8ba2d1e6d709429dad52c29ed74575501588f9c3cc969f1b919b7d0c373f2d1785fec4afad34a236ffaff943566

test:
  secret_key_base: fd26dd8bd81cd52902811f7eb9e0c623f96d1ba790dce996f0aff39063323a4588d620a70299217c2b9981c123c78eb2fdcdcb1bb7c3cd6cf688dea7006ae89c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
